---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Route53 controller is a service controller for managing
    Route53 resources in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Route53
description: |-
  Manage Route53 resources in AWS from within your Kubernetes cluster.


  **About Amazon Route53**


  Amazon Route 53 is a highly available and scalable Domain Name System (DNS) web service. You can use Route 53 to perform three main functions in any combination: domain registration, DNS routing, and health checking.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples: []
maintainers:
- name: "eks maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon Route53 Developer Resources
  url: https://docs.aws.amazon.com/route53/index.html
