// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CidrCollectionSpec defines the desired state of CidrCollection.
//
// A complex type that identifies a CIDR collection.
type CIDRCollectionSpec struct {

	// Information about changes to a CIDR collection.
	// +kubebuilder:validation:Required
	Locations []*CIDRCollectionChange `json:"locations"`
	// A unique identifier for the account that can be used to reference the collection
	// from other API calls.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
}

// CIDRCollectionStatus defines the observed state of CIDRCollection
type CIDRCollectionStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// +kubebuilder:validation:Optional
	CallerReference *string `json:"callerReference,omitempty"`
	// A complex type that contains information about the CIDR collection.
	// +kubebuilder:validation:Optional
	Collection *CIDRCollection_SDK `json:"collection,omitempty"`
	// A unique URL that represents the location for the CIDR collection.
	// +kubebuilder:validation:Optional
	Location *string `json:"location,omitempty"`
}

// CIDRCollection is the Schema for the CIDRCollections API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type CIDRCollection struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CIDRCollectionSpec   `json:"spec,omitempty"`
	Status            CIDRCollectionStatus `json:"status,omitempty"`
}

// CIDRCollectionList contains a list of CIDRCollection
// +kubebuilder:object:root=true
type CIDRCollectionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CIDRCollection `json:"items"`
}

func init() {
	SchemeBuilder.Register(&CIDRCollection{}, &CIDRCollectionList{})
}
