// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TrafficPolicySpec defines the desired state of TrafficPolicy.
//
// A complex type that contains settings for a traffic policy.
type TrafficPolicySpec struct {
	// (Optional) Any comments that you want to include about the traffic policy.
	Comment *string `json:"comment,omitempty"`
	// The definition of this traffic policy in JSON format. For more information,
	// see Traffic Policy Document Format (https://docs.aws.amazon.com/Route53/latest/APIReference/api-policies-traffic-policy-document-format.html).
	// +kubebuilder:validation:Required
	Document *string `json:"document"`
	// The name of the traffic policy.
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
}

// TrafficPolicyStatus defines the observed state of TrafficPolicy
type TrafficPolicyStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRS managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The ID that Amazon Route 53 assigned to a traffic policy when you created
	// it.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty"`
	// The DNS type of the resource record sets that Amazon Route 53 creates when
	// you use a traffic policy to create a traffic policy instance.
	// +kubebuilder:validation:Optional
	Type *string `json:"type_,omitempty"`
	// The version number that Amazon Route 53 assigns to a traffic policy. For
	// a new traffic policy, the value of Version is always 1.
	// +kubebuilder:validation:Optional
	Version *int64 `json:"version,omitempty"`
}

// TrafficPolicy is the Schema for the TrafficPolicies API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type TrafficPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TrafficPolicySpec   `json:"spec,omitempty"`
	Status            TrafficPolicyStatus `json:"status,omitempty"`
}

// TrafficPolicyList contains a list of TrafficPolicy
// +kubebuilder:object:root=true
type TrafficPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrafficPolicy `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TrafficPolicy{}, &TrafficPolicyList{})
}
