// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package hosted_zone

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	compareTags(delta, a, b)

	if ackcompare.HasNilDifference(a.ko.Spec.DelegationSetID, b.ko.Spec.DelegationSetID) {
		delta.Add("Spec.DelegationSetID", a.ko.Spec.DelegationSetID, b.ko.Spec.DelegationSetID)
	} else if a.ko.Spec.DelegationSetID != nil && b.ko.Spec.DelegationSetID != nil {
		if *a.ko.Spec.DelegationSetID != *b.ko.Spec.DelegationSetID {
			delta.Add("Spec.DelegationSetID", a.ko.Spec.DelegationSetID, b.ko.Spec.DelegationSetID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.HostedZoneConfig, b.ko.Spec.HostedZoneConfig) {
		delta.Add("Spec.HostedZoneConfig", a.ko.Spec.HostedZoneConfig, b.ko.Spec.HostedZoneConfig)
	} else if a.ko.Spec.HostedZoneConfig != nil && b.ko.Spec.HostedZoneConfig != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.HostedZoneConfig.Comment, b.ko.Spec.HostedZoneConfig.Comment) {
			delta.Add("Spec.HostedZoneConfig.Comment", a.ko.Spec.HostedZoneConfig.Comment, b.ko.Spec.HostedZoneConfig.Comment)
		} else if a.ko.Spec.HostedZoneConfig.Comment != nil && b.ko.Spec.HostedZoneConfig.Comment != nil {
			if *a.ko.Spec.HostedZoneConfig.Comment != *b.ko.Spec.HostedZoneConfig.Comment {
				delta.Add("Spec.HostedZoneConfig.Comment", a.ko.Spec.HostedZoneConfig.Comment, b.ko.Spec.HostedZoneConfig.Comment)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.HostedZoneConfig.PrivateZone, b.ko.Spec.HostedZoneConfig.PrivateZone) {
			delta.Add("Spec.HostedZoneConfig.PrivateZone", a.ko.Spec.HostedZoneConfig.PrivateZone, b.ko.Spec.HostedZoneConfig.PrivateZone)
		} else if a.ko.Spec.HostedZoneConfig.PrivateZone != nil && b.ko.Spec.HostedZoneConfig.PrivateZone != nil {
			if *a.ko.Spec.HostedZoneConfig.PrivateZone != *b.ko.Spec.HostedZoneConfig.PrivateZone {
				delta.Add("Spec.HostedZoneConfig.PrivateZone", a.ko.Spec.HostedZoneConfig.PrivateZone, b.ko.Spec.HostedZoneConfig.PrivateZone)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VPC, b.ko.Spec.VPC) {
		delta.Add("Spec.VPC", a.ko.Spec.VPC, b.ko.Spec.VPC)
	} else if a.ko.Spec.VPC != nil && b.ko.Spec.VPC != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.VPC.VPCID, b.ko.Spec.VPC.VPCID) {
			delta.Add("Spec.VPC.VPCID", a.ko.Spec.VPC.VPCID, b.ko.Spec.VPC.VPCID)
		} else if a.ko.Spec.VPC.VPCID != nil && b.ko.Spec.VPC.VPCID != nil {
			if *a.ko.Spec.VPC.VPCID != *b.ko.Spec.VPC.VPCID {
				delta.Add("Spec.VPC.VPCID", a.ko.Spec.VPC.VPCID, b.ko.Spec.VPC.VPCID)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.VPC.VPCRegion, b.ko.Spec.VPC.VPCRegion) {
			delta.Add("Spec.VPC.VPCRegion", a.ko.Spec.VPC.VPCRegion, b.ko.Spec.VPC.VPCRegion)
		} else if a.ko.Spec.VPC.VPCRegion != nil && b.ko.Spec.VPC.VPCRegion != nil {
			if *a.ko.Spec.VPC.VPCRegion != *b.ko.Spec.VPC.VPCRegion {
				delta.Add("Spec.VPC.VPCRegion", a.ko.Spec.VPC.VPCRegion, b.ko.Spec.VPC.VPCRegion)
			}
		}
	}

	return delta
}
